CREATE DATABASE BOOKMANAGEMENTSYSTEM;
USE BOOKMANAGEMENTSYSTEM;
CREATE TABLE AUTHOR
(
NAME VARCHAR(255),
ADDRESS VARCHAR(255)NOT NULL UNIQUE,
URL VARCHAR(255),
PRIMARY KEY(NAME,ADDRESS)
);
CREATE TABLE PUBLISHER
(
NAME VARCHAR(255),
ADDRESS VARCHAR(255),
PHONE VARCHAR(255),
URL INT,
PRIMARY KEY(NAME),
)
CREATE TABLE BOOK
(
ISBN VARCHAR(255),
PUBLISHERNAME VARCHAR(255)NOT NULL REFERENCES PUBLISHER(NAME),
AUTHORNAME VARCHAR(255)NOT NULL REFERENCES AUTHOR(NAME),
AUTHORADDRESS VARCHAR(255)NOT NULL REFERENCES AUTHOR(ADDRESS),
YEAR INT,
TITLE VARCHAR(255),
PRICE NUMERIC(19,0)
PRIMARY KEY(ISBN)
)
CREATE TABLE CUSTOMER
(
EMAIL VARCHAR(255),
NAME VARCHAR(255),
PHONE VARCHAR(255),
ADDRESS VARCHAR(255),
PRIMARY KEY(EMAIL)
)
CREATE TABLE SHOPPINGBASKET
(
	ID INT,
	CUSTOMEREMAIL VARCHAR(255) NOT NULL REFERENCES CUSTOMER(EMAIL)
	PRIMARY KEY(ID)
)
CREATE TABLE SHOPPINGBASKET_BOOK
(
	SHOPPINGBASKETID INT NOT NULL REFERENCES SHOPPINGBASKET(ID),
	BOOKISBN VARCHAR(255) NOT NULL REFERENCES BOOK(ISBN)
)
CREATE TABLE WAREHOUSE
(
	CODE INT,
	PHONE VARCHAR(255),
	ADDRESS VARCHAR(255),
	PRIMARY KEY(Code)
)
CREATE TABLE WAREHOUSE_BOOK
(
	WAREHOUSECODE int NOT NULL REFERENCES WAREHOUSE(CODE),
	BOOKISBN VARCHAR(255) NOT NULL REFERENCES BOOK(ISBN),
	COUNT INT
)